Repository sheinsight/shineout, pull requests merged in 2019-12, with the labels that each got.

#443 Theme
  src/styles/card.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: theme

#442 add shape="bordered"
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
  src/Tabs/Header.js
  src/Tabs/Tab.js
  src/Tabs/Tabs.js
  src/styles/tabs.less
  src/styles/themes/bootstrap.less
Labels: feature

#448 Card
  src/Card/Accordion.js
Labels: bug

#447 Table
  src/Table/SimpleTable.js
  src/Table/Table.js
Labels: bug

#446 Datepicker
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Day.js
Labels: bug

#445 Button
  src/Button/Button.js
Labels: bug

#444 Select
  site/pages/components/Popover/example-1-base.js
  src/List/LazyList.js
  src/Select/BoxList.js
  src/styles/select.less
Labels: feature

#449 fix: no color
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tabs/Tab.js
Labels: bug

#450 AbsoluteList
  site/pages/documentation/changelog-rc/1.x.x.md
  src/List/AbsoluteList.js
Labels: bug

#456 Button
  src/styles/button.less
Labels: bug

#455 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SimpleTable.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.loading.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Table/__snapshots__/Table.rowClassname.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: bug

#454 change doc
  README-zh_CN.md
  README.md
  scripts/build-html.js
  site/images/table.gif
  site/redirect.html
Labels: docs

#452 fix select scroll bug
  src/Select/Select.js
Labels: bug

#459 add Transfer loading
  site/chunks/Components/Transfer.js
  site/pages/components/Transfer/cn.md
  site/pages/components/Transfer/en.md
  site/pages/components/Transfer/example-6-loading.js
  site/pages/components/Transfer/example-6-mloading.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Transfer/Card.js
  src/Transfer/Transfer.js
  src/Transfer/item.js
  src/styles/transfer.less
  test/src/Transfer/__snapshots__/example.spec.js.snap
Labels: add props

#458 hover
  src/Checkbox/CheckItem.js
Labels: bug

#457 fix table expand bug when sorted
  src/Table/Td.js
Labels: bug

#462 Table
  src/Table/SimpleTable.js
Labels: bug

#463 Table Resizing
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
  src/Table/SimpleTable.js
  src/Table/Tbody.js
Labels: bug

#460 input showArrow and coin
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/TreeSelect/cn.md
  site/pages/components/TreeSelect/en.md
  src/Input/Number.js
  src/Input/index.js
  src/Select/filter.js
  src/TreeSelect/filter.js
  src/hoc/coin.js
  src/styles/form.less
  src/utils/tree.js
Labels: add props, bug

#461 add defaultTreeExpandKeys
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/TreeExpand.js
Labels: add props

#465 Modify th sorter position
  site/pages/components/Table/example-15-select-base.js
  site/pages/components/Table/example-15-select-format.js
  site/pages/components/Table/example-17-select-disabled.js
  src/Table/Sorter.js
  src/Table/Thead.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.loading.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Table/__snapshots__/Table.rowClassname.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: performace

#467 Fix tabs disabled bug
  src/Tabs/Header.js
  src/Tabs/Link.js
  src/Tabs/Panel.js
  src/Tabs/Wrapper.js
Labels: bug

#468 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
Labels: bug

#464 add showHitDescendants props
  site/pages/components/TreeSelect/en.md
Labels: add props

#470 change initial time when set defaultTime and fix min bug
  src/DatePicker/Picker.js
  src/DatePicker/Time.js
Labels: bug

#471 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
  src/Table/Tr.js
Labels: bug

#473 add getPopupContainer props
  site/chunks/Components/Popover.js
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/components/Popover/example-10-container.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
  src/utils/dom/isDOMElement.js
  src/utils/dom/popover.js
Labels: add props

#472 fix input blur bug when select can edit
  src/Select/Input.js
Labels: bug

#478 Form ref
  site/chunks/Components/Form.js
  site/pages/components/Form/cn.md
  site/pages/components/Form/en.md
  site/pages/components/Form/example-02-controlform.js
  src/Datum/Form.js
  src/Form/Block.js
  src/Form/Flow.js
  src/Form/Form.js
  src/Form/Item.js
Labels: add props

#477 Select
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Input.js
  src/Select/Result.js
  src/Select/Select.js
Labels: feature

#476 Theme
  src/styles/alert.less
  src/styles/checkinput.less
  src/styles/expose.less
  src/styles/mixins/alerts.less
  src/styles/modal.less
  src/styles/select.less
  src/styles/table.less
  src/styles/tag.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/css-accessors.js
  src/utils/vars-inject.js
Labels: theme

#475 add toggleDuration props
  src/Menu/Item.js
  src/Menu/List.js
  src/Menu/Root.js
Labels: add props

#474 add hideExpandIcon
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Tbody.js
  src/Table/Tr.js
  src/Table/index.js
  src/styles/form.less
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: add props
