Repository sheinsight/shineout, pull requests merged in 2019-10, with the labels that each got.

#360 Table
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/Td.js
Labels: feature

#361 Image
  src/styles/image.less
Labels: bug

#362 Codesandbox
  site/Components/Example/Codesandbox.js
  site/utils/regexp.js
Labels: bug

#363 Select
  src/styles/mixins/caret.less
  src/styles/select.less
Labels: bug

#364 TreeSelect
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tree/Content.js
  src/Tree/List.js
  src/Tree/Tree.js
  src/TreeSelect/TreeSelect.js
  src/TreeSelect/datum.js
Labels: bug

#366 TreeSelect
  site/pages/documentation/changelog-rc/1.x.x.md
  src/TreeSelect/filter.js
  src/utils/tree.js
Labels: bug

#367 changelog
  site/pages/Page.js
  site/pages/documentation/changelog/1.x.x.md
Labels: docs

#369 Theme
  src/Select/filter.js
  src/utils/tree.js
Labels: bug

#371 Pagesize
  site/pages/components/Pagination/cn.md
  site/pages/components/Pagination/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Button/Button.js
  src/Menu/Item.js
  src/Menu/Root.js
  src/Pagination/Item.js
  src/Pagination/Links.js
  src/Pagination/Next.js
  src/Pagination/PageSizeList.js
  src/Pagination/index.js
  src/styles/button.less
Labels: feature

#373 Theme
  src/utils/css-accessors.js
  src/utils/expose.js
  src/utils/vars-inject.js
Labels: feature

#372 docs
  site/chunks/Components/Pagination.js
  site/chunks/Components/Select.js
  site/pages/components/Pagination/example-9-modal.js
  site/pages/components/Select/example-13-modal.js
Labels: docs

#374 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
Labels: bug

#375 Input
  src/Input/Input.js
  test/src/Input/__snapshots__/example.spec.js.snap
Labels: bug

#376 Table
  site/pages/components/Tooltip/example-3-disabled-inner.js
  src/Tooltip/Container.js
  src/styles/table.less
  src/styles/tooltip.less
  test/src/Tooltip/__snapshots__/example.spec.js.snap
Labels: bug

#378 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/button.less
  src/styles/card.less
  src/styles/expose.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
  webpack/loaders/var-polyfill-loader.js
Labels: bug

#379 scroll
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  src/Scroll/Scroll.js
  src/Scroll/index.js
Labels: bug

#381 Upload
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tooltip/Container.js
  src/Upload/Dragger.js
  src/Upload/Upload.js
  src/utils/accept.js
  src/utils/index.js
  test/src/Upload/attrAccept.spec.js
Labels: bug, feature

#382 Upload
  site/chunks/Components/Upload.js
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  site/pages/components/Upload/example-02-image.js
  site/pages/components/Upload/example-11-dragger.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Upload/Dragger.js
  src/Upload/Drop.js
  src/Upload/Upload.js
  src/styles/upload.less
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: feature

#383 Absolute list
  site/pages/documentation/changelog-rc/1.x.x.md
  src/List/AbsoluteList.js
  src/List/List.js
  src/Select/OptionList.js
  src/styles/list.less
Labels: feature

#385 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/OptionList.js
  src/styles/expose.less
  src/styles/table.less
  src/styles/themes/cssvar.less
  src/styles/tree.less
  src/utils/css-accessors.js
  src/utils/vars-inject.js
Labels: feature

#387 AbsoluteList
  src/Cascader/Cascader.js
Labels: bug

#388 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Tbody.js
Labels: bug

#389 Image
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Image/Image.js
  src/Upload/Upload.js
Labels: bug

#392 TreeTable
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/CheckboxAll.js
  src/Table/Thead.js
  src/Table/TreeExpand.js
Labels: feature

#391 TreeSelect
  src/TreeSelect/TreeSelect.js
  src/TreeSelect/datum.js
Labels: bug

#390 Menu
  README.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Menu/Item.js
  src/Menu/Root.js
Labels: bug

#397 Select
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  src/Select/Result.js
  src/Select/Select.js
Labels: feature

#393 Modal
  src/styles/modal.less
Labels: bug

#395 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/utils/css-accessors.js
  src/utils/vars-inject.js
Labels: bug

#399 feat: table add onSortCancel
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-10-sort.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
  src/Table/Sorter.js
  src/Table/Tr.js
  src/Table/index.js
Labels: feature

#403 Select
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/select.less
Labels: bug

#401 Theme
  src/styles/expose.less
  src/styles/form.less
  src/styles/message.less
  src/styles/table.less
  src/styles/tag.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: bug, feature

#400 fix: horizontal scorll bar
  src/Menu/Root.js
Labels: bug

#404 Select-TreeData
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/OptionTree.js
  src/Tree/Tree.js
Labels: bug

#402 TreeTable
  site/chunks/Components/Table.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-15-select-radio.js
  site/pages/components/Table/example-26-tree0.js
  src/Datum/List.js
  src/Table/Checkbox.js
  src/Table/CheckboxAll.js
  src/Table/Table.js
  src/Table/Td.js
  src/Table/Thead.js
  src/Table/TreeExpand.js
  src/styles/themes/default.less
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: feature

#405 Scroll
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
  src/Table/Tbody.js
  src/Table/Thead.js
  src/Table/Tr.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: bug, feature
