Repository sheinsight/shineout, pull requests merged in 2019-05, with the labels that each got.

#157 bugfix: deepGet path is not exist
  src/index.js
  src/utils/is.js
  src/utils/objects.js
  test/utils/getset.spec.js
Labels: bug

#159 Menu theme dark bug
  site/pages/components/Menu/example-2-horizontal.js
  src/styles/menu.less
Labels: bug

#162 Remove event
  package.json
  src/Checkbox/CheckItem.js
  src/Input/Input.js
  src/Textarea/Textarea.js
Labels: bug

#164 Docs fixed
  site/Header.js
  site/chunks/Components/Checkbox.js
  site/chunks/Components/DatePicker.js
  site/chunks/Components/Form.js
  site/chunks/Components/Radio.js
  site/chunks/Components/Select.js
  site/index.html
  site/pages/components/Breadcrumb/example-1-base.js
  site/pages/components/Breadcrumb/example-3-icon.js
  site/pages/components/Button/example-6-href.js
  site/pages/components/Checkbox/example-07-datum.js
  site/pages/components/DatePicker/example-04-day.js
  site/pages/components/Datum.Form/cn.md
  site/pages/components/Datum.Form/en.md
  site/pages/components/Form/example-07-validate.js
  site/pages/components/Form/example-08-validate.js
  site/pages/components/Radio/example-4-datum.js
  site/pages/components/Select/example-03-datum.js
  site/styles/markdown.less
  test/src/Breadcrumb/__snapshots__/Breadcrumb.spec.js.snap
Labels: docs

#166 Docs
  site/less-entry.js
  src/Image/Gallery.js
  webpack/config.dev.js
  webpack/config.doc.js
Labels: bug

#163 AbsoluteList
  src/List/AbsoluteList.js
  src/Select/Select.js
  src/styles/treeSelect.less
Labels: bug

#173 TreeSelect
  src/List/AbsoluteList.js
  src/Select/OptionTree.js
  src/Select/Select.js
  src/TreeSelect/TreeSelect.js
Labels: bug

#171 Tree-Table
  package.json
  site/chunks/Components/Table.js
  site/pages/components/Card/cn.md
  site/pages/components/Card/en.md
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-26-tree.js
  src/Card/Body.js
  src/Card/index.js
  src/Table/SeperateTable.js
  src/Table/Td.js
  src/Table/Tr.js
  src/Table/TreeExpand.js
  src/Table/index.js
  src/index.js
  src/styles/card.less
  src/styles/table.less
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: add props

#169 body-style
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  src/Modal/Panel.js
Labels: add props

#175 DatePicker
  src/DatePicker/Container.js
Labels: bug

#174 Upload
  package.json
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  src/Upload/Dragger.js
  src/Upload/Image.js
  src/Upload/Progress.js
  src/Upload/Upload.js
  src/styles/upload.less
Labels: add props

#177 Datum.hoc
  src/Datum/hoc.js
  src/Table/Table.js
Labels: bug

#179 input digits
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  src/Input/Number.js
Labels: add props

#178 Datum
  src/Datum/hoc.js
  src/Table/Table.js
Labels: bug

#188 Flow validate
  src/Datum/Form.js
  src/Datum/types.js
  src/Form/Form.js
  src/Form/formButton.js
  src/Form/index.js
  src/Form/inputable.js
Labels: feature

#189 Datepicker
  package.json
  src/DatePicker/Day.js
  src/DatePicker/Range.js
  src/DatePicker/Time.js
  src/DatePicker/TimeScroll.js
  src/styles/datepicker.less
Labels: bug

#187 Input
  src/hoc/inputBorder.js
Labels: bug

#186 Datum.List
  src/Datum/List.js
Labels: bug

#190 Select
  src/Select/OptionList.js
  src/Select/Select.js
Labels: bug

#193 Select
  src/utils/dom/element.js
Labels: bug

#192 Message
  src/Message/Container.js
  src/Message/index.js
  src/Message/messager.js
  src/Select/Result.js
  src/styles/modal.less
  src/styles/select.less
  test/src/Message/__snapshots__/Message.spec.js.snap
  test/src/Select/Select.clearable.spec.js
Labels: feature

#195 Cascader
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  site/pages/components/Cascader/example-01-base.js
  src/Cascader/Cascader.js
Labels: add props

#197 Cascader
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  src/Cascader/Result.js
  src/styles/cascader.less
Labels: add props, bug

#198 Input number allow null
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  src/Input/Number.js
Labels: add props

#199 Table
  src/Table/Tbody.js
  src/styles/themes/antd.less
Labels: bug

#196 button && ga
  dev-server.js
  scripts/build-html.js
  site/index.html
  src/Button/Button.js
  src/styles/button.less
Labels: feature

#205 TreeSelect
  src/Tree/Checkbox.js
  src/Tree/Content.js
  src/Tree/Tree.js
  src/TreeSelect/TreeSelect.js
Labels: add props

#206 Cascader
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  src/Cascader/Cascader.js
  src/Cascader/Node.js
Labels: bug

#207 feat: Form.FieldSet add onError
  package.json
  src/Form/FieldSet.js
Labels: feature
