Repository sheinsight/shineout, pull requests merged in 2019-11, with the labels that each got.

#406 TreeTable
  site/pages/components/Table/example-26-tree0.js
  src/Table/Table.js
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: bug

#407 Table
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/Tr.js
  src/Table/TreeExpand.js
  src/utils/transform.js
Labels: bug, feature

#408 Spin
  site/chunks/Components/Spin.js
  site/pages/components/Spin/example-01-wrapper.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Spin/index.js
  src/styles/index.js
  src/styles/spin.less
  test/src/Spin/__snapshots__/example.spec.js.snap
Labels: feature

#412 Button
  src/Button/Button.js
  src/styles/button.less
Labels: feature

#411 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/card.less
  src/styles/form.less
  src/styles/menu.less
  src/styles/select.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/styles/treeSelect.less
  src/utils/vars-inject.js
Labels: feature

#410 Tree
  src/Tree/Node.js
Labels: bug

#409 Select
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  src/Select/Select.js
Labels: feature

#413 AbsoluteList
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Lazyload/index.js
  src/List/AbsoluteList.js
  src/utils/vars-inject.js
Labels: bug

#419 Cascader
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Result.js
Labels: bug

#418 TreeExpand
  site/pages/components/Tree/cn.md
  site/pages/components/Tree/en.md
  site/pages/components/Tree/example-02-icon.js
  src/Tree/Content.js
  src/Tree/Tree.js
  test/src/Tree/__snapshots__/Tree.spec.js.snap
Labels: feature

#414 Table
  src/Table/Thead.js
Labels: bug

#416 Tree
  src/styles/tree.less
Labels: bug

#420 remove runtime
  package.json
  yarn.lock
Labels: bug

#421 Modal
  site/chunks/Components/Modal.js
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/components/Modal/example-3-gcontainer.js
  site/pages/components/Tree/cn.md
  site/pages/components/Tree/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Modal/events.js
Labels: feature

#422 changelog
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  site/pages/documentation/changelog/1.x.x.md
Labels: changelog

#427 tree iconClass
  site/pages/components/Tree/cn.md
  site/pages/components/Tree/en.md
  src/Tree/Content.js
  src/Tree/Tree.js
Labels: feature

#426 Span wrap
  src/Button/Button.js
  src/Tag/Tag.js
  src/utils/dom/element.js
  test/src/Button/__snapshots__/example.spec.js.snap
  test/src/Dropdown/__snapshots__/example.spec.js.snap
  test/src/Input/__snapshots__/example.spec.js.snap
  test/src/Modal/__snapshots__/Modal.type.spec.js.snap
  test/src/Progress/__snapshots__/example.spec.js.snap
  test/src/Tag/__snapshots__/example.spec.js.snap
  test/src/Tooltip/__snapshots__/example.spec.js.snap
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: bug

#424 Table
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/SimpleTable.js
  src/Table/Table.js
  src/Table/Tr.js
  src/Table/resizable.js
  src/styles/table.less
  test/src/Table/Table.spec.js
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.loading.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Table/__snapshots__/Table.rowClassname.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: feature

#425 Transfer
  site/chunks/Components/Transfer.js
  site/chunks/Components/index.js
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Table/cn.md
  site/pages/components/Transfer/cn.md
  site/pages/components/Transfer/en.md
  site/pages/components/Transfer/example-1-base.js
  site/pages/components/Transfer/example-2-controlled.js
  site/pages/components/Transfer/example-3-customTitle.js
  site/pages/components/Transfer/example-4-selected.js
  site/pages/components/Transfer/example-5-filter.js
  site/pages/components/group.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Transfer/Card.js
  src/Transfer/Transfer.js
  src/Transfer/btns.js
  src/Transfer/context.js
  src/Transfer/index.js
  src/Transfer/item.js
  src/Transfer/select.js
  src/index.js
  src/locale/en_US.js
  src/locale/zh-CN.js
  src/styles/index.js
  src/styles/transfer.less
  src/utils/func.js
Labels: New Component

#431 Upload
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Upload/Progress.js
  src/styles/spin.less
  src/styles/upload.less
Labels: bug

#430 Theme
  src/styles/card.less
  src/styles/expose.less
  src/styles/modal.less
  src/styles/popover.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: theme

#428 Select
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  src/Select/Result.js
  src/Select/Select.js
Labels: bug

#429 transfer
  site/chunks/Components/index.js
  site/pages/components/Transfer/example-4-selected.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/List.js
  src/Transfer/Transfer.js
  src/Transfer/btns.js
  test/src/Transfer/Trasnfer.spec.jss
  test/src/Transfer/__snapshots__/example.spec.js.snap
  test/src/Transfer/example.spec.js
Labels: feature

#432 Button
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Button/Button.js
Labels: bug

#436 Table
  src/Scroll/Scroll.js
Labels: bug

#435 Popover
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
Labels: add props

#434 Theme
  src/styles/modal.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: theme

#433 Select
  src/Select/Result.js
Labels: bug

#437 Tooltip
  src/styles/tooltip.less
Labels: bug

#438 Tabs
  site/pages/components/Tabs/cn.md
  site/pages/components/Tabs/en.md
  site/pages/components/Tabs/example-03-color.js
  src/Tabs/Panel.js
  src/Tabs/Tabs.js
Labels: feature

#439 CardGroup
  site/chunks/Components/CardGroup.js
  site/chunks/Components/index.js
  site/pages/components/CardGroup/cn.md
  site/pages/components/CardGroup/en.md
  site/pages/components/CardGroup/example-1-base.js
  site/pages/components/CardGroup/example-2-width.js
  site/pages/components/CardGroup/example-3-lazyload.js
  site/pages/components/CardGroup/example-4-checkbox.js
  site/pages/components/Icon/Shineout.js
  site/pages/components/group.json
  src/CardGroup/CardGroup.js
  src/CardGroup/Item.js
  src/CardGroup/context.js
  src/CardGroup/index.js
  src/Lazyload/index.js
  src/index.js
  src/styles/cardGroup.less
  src/styles/index.js
Labels: feature

#440 Select
  src/Select/Input.js
Labels: bug

#441 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SimpleTable.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
Labels: bug
