Repository sheinsight/shineout, pull requests merged in 2019-07, with the labels that each got.

#238 Select
  src/Select/Select.js
Labels: bug

#243 Select-Compressed
  src/Cascader/Cascader.js
  src/Cascader/Result.js
  src/DatePicker/Container.js
  src/Select/Result.js
  src/TreeSelect/Result.js
  src/styles/cascader.less
  src/styles/datepicker.less
  src/styles/select.less
  src/styles/treeSelect.less
Labels: bug

#241 antd2
  src/styles/progress.less
  src/styles/tabs.less
  src/styles/themes/antd2.less
  src/styles/themes/bootstrap.less
Labels: feature

#237 Message
  site/chunks/Components/Table.js
  site/pages/components/Form/example-15-fieldset.js
  site/pages/components/Table/example-27-tree.js
  site/pages/components/Table/example-28-sort.js
  src/Message/Container.js
  src/Message/index.js
  src/utils/is.js
  test/src/Message/__snapshots__/Message.spec.js.snap
Labels: feature

#247 Pagination select
  package.json
  src/Pagination/PageSizeList.js
  test/src/Pagination/Pagination.spec.js
  test/src/Pagination/__snapshots__/example.spec.js.snap
  test/src/Pagination/example.spec.js
Labels: bug

#248 Select
  src/Select/Input.js
  src/Select/Result.js
  src/Select/Select.js
Labels: add props

#249 select list autoAdapt
  site/chunks/Components/Select.js
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Select/example-01-cadapt.js
  src/List/AbsoluteList.js
  src/Pagination/PageSizeList.js
  src/Select/OptionList.js
  src/Select/Select.js
  src/styles/select.less
Labels: add props

#252 Select
  src/Select/Input.js
  src/styles/select.less
  src/utils/dom/element.js
Labels: bug

#250 Switch
  site/chunks/Components/Switch.js
  site/chunks/Components/index.js
  site/pages/components/Switch/cn.md
  site/pages/components/Switch/en.md
  site/pages/components/Switch/example-1-base.js
  site/pages/components/Switch/example-2-disabled.js
  site/pages/components/Switch/example-3-content.js
  site/pages/components/Switch/example-4-size.js
  site/pages/components/group.json
  src/Checkbox/CheckItem.js
  src/Switch/Switch.js
  src/Switch/index.js
  src/index.js
  src/styles/checkinput.less
  src/styles/themes/antd.less
  src/styles/themes/bootstrap.less
Labels: New Component

#257 feature: form item tabindex
  src/Button/Group.js
  src/Button/Once.js
  src/Cascader/Cascader.js
  src/Cascader/List.js
  src/Cascader/Result.js
  src/Checkbox/CheckItem.js
  src/Checkbox/Group.js
  src/Checkbox/context.js
  src/Checkbox/index.js
  src/DatePicker/Container.js
  src/DatePicker/Text.js
  src/DatePicker/value.js
  src/Input/Number.js
  src/Scroll/Scroll.js
  src/Select/Input.js
  src/Select/Option.js
  src/Select/Result.js
  src/Select/Select.js
  src/Tree/Content.js
  src/TreeSelect/Result.js
  src/TreeSelect/TreeSelect.js
  src/Upload/Image.js
  src/Upload/Progress.js
  src/Upload/Upload.js
  src/hoc/inputBorder.js
  src/styles/cascader.less
  src/styles/checkinput.less
  src/styles/datepicker.less
  src/styles/form.less
  src/styles/mixins/buttons.less
  src/styles/mixins/forms.less
  src/styles/themes/bootstrap.less
  src/styles/tree.less
  src/styles/upload.less
  src/utils/is.js
  test/src/DatePicker/DatePicker.spec.js
Labels: feature

#256 Popover
  src/Popover/Panel.js
  src/styles/popover.less
  src/utils/dom/popover.js
Labels: bug

#255 Table
  src/Table/SeperateTable.js
Labels: bug

#254 Cascader
  src/Cascader/Cascader.js
Labels: bug

#253 Popover.Confirm
  site/chunks/Components/Popover.js
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/components/Popover/example-4-confirm.js
  site/pages/components/Popover/example-5-func.js
  site/pages/components/Popover/example-5-type.js
  site/pages/components/Popover/example-6-type.js
  site/pages/components/Popover/example-7-type.js
  site/pages/components/Popover/example-8-old.js
  site/pages/components/Popover/example-9-event.js
  src/Popover/Confirm.js
  src/Popover/index.js
  src/styles/popover.less
Labels: feature

#259 Pagination
  src/Pagination/Jumper.js
Labels: bug

#261 Datum.Form
  src/Datum/Form.js
Labels: bug

#260 Image
  src/Image/Magnify.js
  src/styles/image.less
  test/src/Image/Magnify.spec.js
Labels: feature

#258 fixed: range time & upload docs
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  src/DatePicker/Range.js
  src/DatePicker/utils.js
  src/Upload/Upload.js
  test/src/DatePicker/DatePicker.spec.js
Labels: feature

#264 fixed: form onchange && popover render
  src/Datum/Form.js
  src/Form/Form.js
  src/Popover/Panel.js
  test/src/Form/Form.spec.js
  test/src/Popover/Popover.spec.js
  test/src/Popover/Popover.type.spec.js
Labels: bug

#263 Select
  src/Select/Input.js
Labels: bug

#265 Rules
  src/Datum/List.js
  src/Form/inputable.js
Labels: bug

#262 Docs
  site/chunks/Components/Button.js
  site/chunks/Components/Checkbox.js
  site/chunks/Components/Form.js
  site/chunks/Components/Popover.js
  site/chunks/Components/Radio.js
  site/chunks/Components/Select.js
  site/pages/Page.js
  site/pages/components/Button/example-1-base.js
  site/pages/components/Button/example-2-icon.js
  site/pages/components/Button/example-3-size.js
  site/pages/components/Button/example-4-disabled.js
  site/pages/components/Button/example-7-icon.js
  site/pages/components/Button/example-7-outline.js
  site/pages/components/Checkbox/cn.md
  site/pages/components/Checkbox/en.md
  site/pages/components/Checkbox/example-07-datum.js
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/Form/example-04-inline.js
  site/pages/components/Form/example-93-validate.js
  site/pages/components/Input/example-7-validate.js
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/components/Popover/example-1-controll.js
  site/pages/components/Popover/example-2-delay.js
  site/pages/components/Radio/cn.md
  site/pages/components/Radio/en.md
  site/pages/components/Radio/example-4-datum.js
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Select/example-01-multiple.js
  site/pages/components/Select/example-03-datum.js
  test/src/Button/Button.spec.js
  test/src/Button/__snapshots__/example.spec.js.snap
  test/src/Checkbox/Checkbox.spec.js
  test/src/Checkbox/__snapshots__/example.spec.js.snap
  test/src/Radio/Radio.spec.js
  test/src/Radio/__snapshots__/example.spec.js.snap
Labels: docs

#268 Select
  src/Select/Result.js
  src/TreeSelect/Result.js
  src/styles/select.less
  src/styles/treeSelect.less
Labels: feature

#269 feature: Datepicker range change
  package.json
  site/chunks/Components/DatePicker.js
  site/chunks/Components/Textarea.js
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/DatePicker/example-04-minmax.js
  site/pages/components/DatePicker/example-05-week.js
  site/pages/components/DatePicker/example-09-range-date.js
  site/pages/components/DatePicker/example-09-single.js
  site/pages/components/DatePicker/example-09-squick.js
  site/pages/components/Textarea/cn.md
  site/pages/components/Textarea/en.md
  site/pages/components/Textarea/example-3-info.js
  site/pages/components/Textarea/example-4-custom.js
  src/DatePicker/Container.js
  src/DatePicker/Day.js
  src/DatePicker/Month.js
  src/DatePicker/Picker.js
  src/DatePicker/Range.js
  src/DatePicker/Time.js
  src/DatePicker/Year.js
  src/DatePicker/utils.js
  src/DatePicker/value.js
  src/Textarea/Textarea.js
  src/locale/en_US.js
  src/locale/zh-CN.js
  src/styles/datepicker.less
  src/styles/themes/bootstrap.less
  test/src/DatePicker/DatePicker.spec.js
  test/src/Dropdown/Dropdown.spec.js
  test/src/Textarea/Textarea.spec.js
  test/src/Textarea/__snapshots__/example.spec.js.snap
Labels: feature

#274 Progress
  src/Progress/Circle.js
  test/src/Progress/__snapshots__/example.spec.js.snap
Labels: bug

#275 fixed: select result click close
  src/Select/Select.js
Labels: bug

#273 Table
  site/chunks/Components/Table.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-28-tree.js
  site/pages/components/Table/example-29-sort.js
  src/Table/TreeExpand.js
  src/styles/form.less
Labels: feature

#272 doc: support rc doc
  package.json
  site/Header.js
  site/pages/documentation/changelog-rc/1.x.x.md
  site/pages/documentation/index.js
  webpack/config.common.js
Labels: docs

#276 doc: rc.3 changlog
  site/Components/Navable/index.js
  site/pages/documentation/changelog-rc/1.x.x.md
Labels: docs

#271 Form
  site/chunks/Components/Form.js
  site/pages/components/Form/example-09-server-validate.js
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  src/Card/Card.js
  src/Card/Submit.js
  src/Datum/Form.js
  src/Form/Form.js
  src/Form/formButton.js
  src/Form/index.js
  src/Form/inputable.js
  src/utils/dom/element.js
  src/utils/flat.js
Labels: bug

#278 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
Labels: bug
