Repository sheinsight/shineout, pull requests merged in 2019-06, with the labels that each got.

#208 Select
  src/Select/Select.js
  src/styles/cascader.less
  src/styles/table.less
Labels: bug

#209 DatePicker
  src/DatePicker/Range.js
  src/Menu/Item.js
  src/Menu/Root.js
  src/styles/datepicker.less
Labels: bug

#211 Datum.List
  src/Datum/List.js
Labels: bug

#212 Table
  src/Table/SeperateTable.js
  src/Tree/Content.js
Labels: bug

#213 changelog
  site/pages/documentation/changelog/1.x.x.md
Labels: changelog

#170 Docs
  site/chunks/Components/Checkbox.js
  site/chunks/Components/DatePicker.js
  site/chunks/Components/Form.js
  site/chunks/Components/Modal.js
  site/chunks/Components/Radio.js
  site/chunks/Components/Select.js
  site/chunks/Components/Tabs.js
  site/pages/components/Breadcrumb/example-1-base.js
  site/pages/components/Breadcrumb/example-3-icon.js
  site/pages/components/Cascader/example-01-base.js
  site/pages/components/Checkbox/example-07-datum.js
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/DatePicker/example-02-format.js
  site/pages/components/Form/cn.md
  site/pages/components/Form/en.md
  site/pages/components/Form/example-07-validate.js
  site/pages/components/Form/example-08-validate.js
  site/pages/components/Form/example-09-validate.js
  site/pages/components/Modal/example-1-base.js
  site/pages/components/Radio/example-4-datum.js
  site/pages/components/Select/example-03-datum.js
  site/pages/components/Select/example-17-result.js
  site/pages/components/Tabs/example-02-disable.js
  site/pages/components/Tabs/example-03-color.js
  site/pages/components/Tabs/example-04-scroll.js
  site/pages/components/Tabs/example-05-active.js
  site/pages/components/Tabs/example-06-shape-line.js
  site/pages/components/Tabs/example-07-shape-button.js
  site/pages/components/Tabs/example-08-align-right.js
  site/pages/components/Tabs/example-09-align-vertical-left.js
  site/pages/components/Tabs/example-10-align-vertical-right.js
  site/pages/components/Tabs/example-11-collapsible.js
  site/pages/components/Tabs/example-12-link.js
  test/src/Breadcrumb/__snapshots__/Breadcrumb.spec.js.snap
  test/src/Tabs/Tabs.spec.js
Labels: docs

#194 sort the api
  site/Components/Table.js
Labels: docs

#214 cascader data
  site/pages/components/Cascader/example-01-base.js
Labels: docs

#215 Select
  src/Select/Select.js
Labels: bug

#216 Changelog
  site/pages/documentation/changelog/1.x.x.md
Labels: changelog

#218 Menu
  src/Menu/Item.js
  src/Menu/List.js
  src/Menu/Root.js
Labels: bug

#220 Input
  src/Input/Number.js
  test/src/Input/Input.spec.js
Labels: bug

#225 DatePicker
  src/DatePicker/Range.js
Labels: feature

#224 Menu
  src/Menu/Root.js
Labels: bug

#223 Image
  src/Image/Image.js
Labels: add props

#226 field-set
  site/pages/components/Form/example-16-fieldset.js
  src/Checkbox/CheckItem.js
  src/Datum/Form.js
Labels: bug, feature

#229 feat: Form add removeUndefined props
  package.json
  site/pages/components/Form/cn.md
  site/pages/components/Form/en.md
  site/pages/components/Form/example-01-base.js
  site/pages/documentation/changelog/1.x.x.md
  src/Datum/Form.js
  src/Form/index.js
  src/index.js
  src/utils/clone.js
Labels: feature

#227 Table
  src/Table/SeperateTable.js
  src/styles/table.less
Labels: bug

#228 Select
  src/Select/Input.js
  src/Tooltip/events.js
Labels: bug

#231 zIndex
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/TreeSelect/cn.md
  site/pages/components/TreeSelect/en.md
  src/Cascader/Cascader.js
  src/DatePicker/Container.js
  src/List/AbsoluteList.js
  src/Modal/events.js
  src/Select/Select.js
  src/TreeSelect/TreeSelect.js
Labels: add props

#232 zIndex
  src/Cascader/Cascader.js
  src/DatePicker/Container.js
  src/List/AbsoluteList.js
  src/Modal/events.js
  src/TreeSelect/TreeSelect.js
Labels: add props

#219 Rate
  src/Rate/Rate.js
  src/Rate/index.js
Labels: feature

#234 Modal width auto
  package.json
  src/Modal/Panel.js
  src/styles/modal.less
  test/src/Modal/__snapshots__/Modal.spec.js.snap
  test/src/Modal/__snapshots__/Modal.type.spec.js.snap
Labels: bug

#233 Menu
  src/Menu/Root.js
Labels: bug

#236 TreeTable
  src/Table/TreeExpand.js
Labels: bug, feature
