Repository sheinsight/shineout, pull requests merged in 2019-04, with the labels that each got.

#115 Upload
  package.json
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  site/pages/components/Upload/example-01-base.js
  site/pages/components/Upload/example-04-validator.js
  site/pages/components/Upload/example-05-filesize.js
  src/Upload/Image.js
  src/Upload/Upload.js
  test/src/Upload/Upload.spec.js
Labels: add props

#118 Datepicker
  package.json
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/DatePicker/example-13-absolute.js
  src/DatePicker/Container.js
  src/DatePicker/Day.js
Labels: add props

#117 select absolute
  site/pages/components/Select/example-14-columns.js
  src/Select/AbsoluteList.js
  src/Select/BoxOption.js
Labels: bug

#116 CI
  .travis.yml
  test/src/DatePicker/DatePicker.spec.js
  test/src/Slider/__snapshots__/example.spec.js.snap
Labels: add CI

#119 Upload
  package.json
  site/chunks/Components/Upload.js
  site/pages/components/Table/cn.md
  site/pages/components/Upload/example-11-dragger.js
  src/Upload/Dragger.js
  src/Upload/Upload.js
  src/Upload/context.js
  src/Upload/index.js
  src/styles/upload.less
  test/src/Upload/__snapshots__/example.spec.js.snap
  test/src/Upload/attrAccept.spec.js
Labels: feature

#121 add changelog
  site/pages/documentation/changelog/0.x.x.md
  site/pages/documentation/changelog/1.x.x.md
Labels: changelog

#120 Table
  src/Table/SeperateTable.js
Labels: add props

#112 react & search
  package.json
  scripts/build-html.js
  site/Components/Navable/index.js
  site/Header.js
  site/index.html
  site/pages/Page.js
  site/redirect.html
  site/styles/header.less
  yarn.lock
Labels: docs

#126 dropdown-size align
  src/Dropdown/index.js
  src/styles/dropdown.less
  test/src/Dropdown/Dropdown.spec.js
  test/src/Dropdown/__snapshots__/example.spec.js.snap
Labels: bug

#125 Select
  package.json
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Select/example-05-multiple.js
  src/Select/Result.js
  src/Select/Select.js
  src/styles/select.less
Labels: add props

#127 Table
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-06-fixed-header.js
  src/Table/Table.js
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: enhance props

#130 docs for search
  scripts/build-html.js
  site/App.js
  site/Components/MarkDown/MarkDown.js
  site/pages/components/Cascader/example-01-base.js
  site/pages/components/Select/example-02-format.js
  site/pages/components/Table/example-01-base.js
  site/pages/components/Tree/example-01-base.js
  site/redirect.html
Labels: docs

#132 Table
  package.json
  src/Table/Tr.js
Labels: bug

#133 DatePicker
  site/pages/components/DatePicker/example-01-base.js
  src/DatePicker/Day.js
  src/DatePicker/Picker.js
  src/DatePicker/Time.js
  src/styles/datepicker.less
Labels: bug

#134 upload bug fixed
  src/Datum/hoc.js
  src/Table/Sorter.js
  src/Upload/Upload.js
Labels: bug

#135 Menu
  package.json
  src/Menu/Root.js
  src/Tooltip/Container.js
Labels: bug

#138 Dropdown
  src/Textarea/Textarea.js
  src/TreeSelect/datum.js
  src/styles/dropdown.less
  src/styles/themes/antd.less
  src/styles/themes/bootstrap.less
Labels: bug

#136 Table
  package.json
  site/pages/components/Table/example-25-row-click-attr.js
  src/Table/SeperateTable.js
  src/Table/Tbody.js
  src/Table/Td.js
  src/Table/Tr.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: bug

#140 TreeSelect
  package.json
  site/pages/components/TreeSelect/cn.md
  site/pages/components/TreeSelect/en.md
  site/pages/components/TreeSelect/example-02-mutiple.js
  src/Popover/Panel.js
  src/TreeSelect/Result.js
  src/TreeSelect/TreeSelect.js
  src/styles/treeSelect.less
Labels: add props

#141 Datepicker
  src/DatePicker/Time.js
  src/DatePicker/value.js
Labels: bug

#143 Select
  package.json
  src/styles/select.less
  src/styles/treeSelect.less
Labels: bug

#147 Table
  package.json
  src/Datum/hoc.js
  src/Scroll/Scroll.js
  src/Table/SeperateTable.js
  src/Table/Table.js
  src/Table/Tbody.js
  src/Table/Td.js
  src/Table/Tr.js
  src/Table/index.js
  src/styles/table.less
  test/src/Select/Select.datum.spec.js
  test/src/Select/Select.format.spec.js
  test/src/Select/v_format.js
  test/src/Table/Table.rowClassname.spec.js
Labels: bug

#148 Image
  site/pages/components/Image/cn.md
  site/pages/components/Image/en.md
  site/pages/components/Textarea/cn.md
  site/pages/components/Textarea/en.md
  src/Image/Image.js
  src/Input/Input.js
  src/Textarea/Textarea.js
  src/locale/en_US.js
  src/locale/zh-CN.js
  src/styles/image.less
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: performace

#129 Build Change
  dev-server.js
  package.json
  webpack/config.common.js
  webpack/config.dev.js
  webpack/config.dist.dev.js
  webpack/config.dist.js
  webpack/config.doc.js
  webpack/loaders/ignore-loader.js
  webpack/loaders/remove-less-loader.js
  webpack/utils/theme.css.js
  yarn.lock
Labels: Build

#153 Tabs
  package.json
  site/chunks/Components/Tabs.js
  site/pages/components/Tabs/example-11-link.js
  src/Menu/Item.js
  src/Tabs/Link.js
  src/Tabs/Tab.js
  src/Tabs/Tabs.js
  src/Tabs/index.js
  src/styles/tabs.less
  src/utils/is.js
Labels: feature

#152 DatePicker
  src/DatePicker/Range.js
  src/DatePicker/value.js
  src/Pagination/index.js
  src/Textarea/Textarea.js
  src/styles/datepicker.less
Labels: bug

#150 add antd2 theme
  config.js
  package.json
  src/styles/icon.less
  src/styles/mixins/caret.less
  src/styles/themes/antd2.less
  yarn.lock
Labels: theme
