Repository sheinsight/shineout, pull requests merged in 2019-09, with the labels that each got.

#319 Features
  site/chunks/Components/Form.js
  site/chunks/Components/Modal.js
  site/chunks/Components/Select.js
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/components/Modal/example-2-special.js
  site/pages/components/Modal/example-3-focus.js
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Select/example-02-group.js
  src/Modal/Panel.js
  src/Modal/events.js
  src/Modal/index.js
  src/Select/Option.js
  src/Select/OptionList.js
  src/Select/Select.js
  src/Select/group.js
  src/Select/index.js
  src/styles/modal.less
  src/styles/select.less
  src/styles/themes/bootstrap.less
  test/src/Modal/Modal.spec.js
  test/src/Modal/Modal.type.spec.js
  test/src/Modal/__snapshots__/Modal.type.spec.js.snap
Labels: add props

#317 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
  src/Popover/events.js
  src/Tooltip/Container.js
  src/Tooltip/events.js
  src/utils/dom/popover.js
Labels: bug

#320 AbsoluteList
  site/pages/documentation/changelog-rc/1.x.x.md
  src/List/AbsoluteList.js
Labels: bug

#321 Table
  src/Table/Tr.js
Labels: bug

#324 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/expose.less
  src/styles/select.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: theme

#323 Table
  src/Table/Thead.js
  src/Table/Tr.js
  src/Tooltip/events.js
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: bug

#325 TreeSelect
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/Tree.js
  src/TreeSelect/filter.js
Labels: bug

#326 Menu
  site/pages/components/Form/cn.md
  site/pages/components/Form/en.md
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  src/Menu/Item.js
  src/Select/index.js
  src/styles/popover.less
Labels: bug

#328 TreeSelect
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/Tree.js
  src/Tree/Tree.js
  src/TreeSelect/TreeSelect.js
  src/TreeSelect/filter.js
Labels: bug

#327 Docs add codesandbox
  package.json
  site/Components/Example/Codesandbox.js
  site/Components/Example/index.js
  site/Components/Example/template.js
  site/chunks/Components/Table.js
  site/data/city.js
  site/data/tree.js
  site/icons/Icon.js
  site/pages/components/Modal/example-5-multistage.js
  site/pages/components/Table/example-18-select.js
  yarn.lock
Labels: docs

#329 DatePicker
  src/DatePicker/Day.js
  src/DatePicker/Range.js
Labels: bug

#333 1.4.1 changelog
  package.json
  site/pages/documentation/changelog/1.x.x.md
Labels: docs

#332 feature: progress gradient
  site/chunks/Components/Progress.js
  site/pages/components/GetStart/cn.md
  site/pages/components/Progress/cn.md
  site/pages/components/Progress/en.md
  site/pages/components/Progress/example-3-linear.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Progress/Circle.js
  src/Progress/Line.js
  src/Progress/analyzeColor.js
  test/src/Progress/__snapshots__/example.spec.js.snap
Labels: feature

#336 fix: image loading
  site/chunks/Components/Image.js
  site/pages/components/Image/cn.md
  site/pages/components/Image/en.md
  site/pages/components/Image/example-09-lazy.js
  site/pages/components/Image/example-10-lazy.js
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  src/Image/Image.js
  src/Modal/events.js
  src/utils/lazyload.js
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: feature

#345 TreeSelect
  site/pages/documentation/changelog-rc/1.x.x.md
  src/TreeSelect/Result.js
  src/styles/treeSelect.less
Labels: feature

#344 datepicker defaultRangeMonth
  site/chunks/Components/DatePicker.js
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/DatePicker/example-09-range-month.js
  site/pages/components/DatePicker/example-09-squick.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Container.js
  src/DatePicker/utils.js
Labels: feature

#337 Table
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/Table.js
  src/Table/Tbody.js
  src/Table/Td.js
  src/Table/Tr.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: bug

#348 Select
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Option.js
  src/TreeSelect/TreeSelect.js
  src/icons/index.js
  src/styles/select.less
  test/src/Select/v_other.js
Labels: bug

#347 Upload
  src/Upload/Progress.js
  src/Upload/Upload.js
  src/styles/upload.less
Labels: bug

#346 Table
  src/utils/shallowEqual.js
Labels: bug

#354 ChildrenKey
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Tree/cn.md
  site/pages/components/Tree/en.md
  site/pages/components/TreeSelect/cn.md
  site/pages/components/TreeSelect/en.md
  src/Cascader/Cascader.js
  src/Cascader/Node.js
  src/Datum/Tree.js
  src/Select/OptionTree.js
  src/Select/Select.js
  src/Tree/Content.js
  src/Tree/Node.js
  src/Tree/Tree.js
  src/Tree/toggle.js
  src/TreeSelect/TreeSelect.js
  src/TreeSelect/datum.js
  src/styles/table.less
Labels: feature

#350 Select tree
  src/Select/OptionTree.js
  src/Tree/Tree.js
Labels: feature

#353 add renderContent
  site/chunks/Components/Upload.js
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  site/pages/components/Upload/example-02-show-image.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Upload/ImageResult.js
  src/Upload/Upload.js
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: feature

#355 Tooltip
  site/chunks/Components/Tooltip.js
  site/pages/components/Tooltip/cn.md
  site/pages/components/Tooltip/en.md
  site/pages/components/Tooltip/example-3-disabled-inner.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tooltip/Container.js
  test/src/Tooltip/__snapshots__/example.spec.js.snap
Labels: feature

#358 Select
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  site/pages/components/Upload/example-02-show-image.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Upload/ImageResult.js
  src/Upload/Upload.js
  src/styles/mixins/caret.less
  src/styles/select.less
Labels: feature

#357 Menu
  package.json
  src/Datum/List.js
  src/Datum/hoc.js
  src/Image/Image.js
  src/Menu/Item.js
  src/Menu/Root.js
  yarn.lock
Labels: bug
