Repository sheinsight/shineout, pull requests merged in 2019-08, with the labels that each got.

#279 Menu
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Menu/Root.js
Labels: bug

#281 Table
  src/Table/SeperateTable.js
Labels: bug

#282 momthRange disable
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Month.js
Labels: bug

#280 Select
  site/chunks/Components/Select.js
  site/pages/components/Select/example-01-multiple.js
  site/pages/components/Select/example-01-o-compressed.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Result.js
  src/styles/select.less
Labels: feature

#277 feature: input clearable
  site/chunks/Components/Input.js
  site/pages/components/Input/example-1-clearable.js
  src/Input/Input.js
  src/Input/clear.js
  src/styles/form.less
  test/src/Input/Input.spec.js
  test/src/Input/__snapshots__/example.spec.js.snap
Labels: feature

#285 fixed: table columns change
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Colgroup.js
  src/Table/SeperateTable.js
  src/Table/Tbody.js
  src/utils/shallowEqual.js
  test/src/Table/Table.rowSection.spec.js
Labels: bug

#283 Rules
  src/Form/inputable.js
Labels: bug

#284 Cascader
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  src/Cascader/Result.js
Labels: feature

#286 Changelog
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
Labels: docs

#288 fixed: cascader right hidden
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Cascader.js
Labels: bug

#287 fixed: datepicker start time disabled
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Day.js
Labels: bug

#290 fixed: datepicker week format change
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/DatePicker/example-05-week.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Container.js
  src/DatePicker/Day.js
  src/DatePicker/utils.js
  src/DatePicker/value.js
  src/locale/en_US.js
  src/locale/zh-CN.js
  test/src/DatePicker/DatePicker.spec.js
Labels: feature

#291 Select
  src/Select/Select.js
  src/Table/Tr.js
  src/styles/select.less
Labels: feature

#293 Select
  src/styles/select.less
Labels: bug

#298 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/events.js
  src/Tooltip/Container.js
  src/Tooltip/events.js
Labels: bug

#299 Dropdown
  site/chunks/Components/Dropdown.js
  site/pages/components/Dropdown/example-7-base.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Dropdown/index.js
  src/List/AbsoluteList.js
  test/src/Dropdown/Dropdown.spec.js
  test/src/Dropdown/example.spec.js
Labels: bug

#295 fixed: Select onCreate bug
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Cascader.js
  src/List/AbsoluteList.js
  src/Select/Select.js
  src/Select/filter.js
  src/styles/cascader.less
  src/utils/dom/element.js
Labels: bug

#300 menu vertical && linkKey
  package.json
  site/chunks/Components/DatePicker.js
  site/chunks/Components/Menu.js
  site/chunks/Components/Table.js
  site/pages/components/DatePicker/example-11-disabled.js
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  site/pages/components/Menu/example-1-link.js
  site/pages/components/Table/example-06-fixed-header.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Cascader.js
  src/Menu/Item.js
  src/Menu/List.js
  src/Menu/Root.js
  src/Scroll/Bar.js
  src/Select/Result.js
  src/Table/SeperateTable.js
  src/Upload/FileInput.js
  src/Upload/Upload.js
  src/styles/menu.less
  test/src/Menu/__snapshots__/example.spec.js.snap
Labels: bug, feature

#304 Tree
  site/pages/components/Tree/cn.md
  site/pages/components/Tree/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tree/Tree.js
  src/TreeSelect/TreeSelect.js
Labels: add props

#306 Custom theme
  site/Components/ThemeEditor/Drawer.js
  site/Components/ThemeEditor/EditorItem.js
  site/Components/ThemeEditor/config.js
  site/Components/ThemeEditor/context.js
  site/Components/ThemeEditor/index.js
  site/Header.js
  site/pages/components/Tree/cn.md
  site/pages/components/Tree/en.md
  site/styles/header.less
  site/styles/index.less
  src/Select/Select.js
  src/styles/alert.less
  src/styles/button.less
  src/styles/card.less
  src/styles/checkinput.less
  src/styles/datepicker.less
  src/styles/dropdown.less
  src/styles/expose.less
  src/styles/form.less
  src/styles/menu.less
  src/styles/message.less
  src/styles/mixins/alerts.less
  src/styles/mixins/buttons.less
  src/styles/mixins/close.less
  src/styles/modal.less
  src/styles/normalize.less
  src/styles/pagination.less
  src/styles/popover.less
  src/styles/select.less
  src/styles/slider.less
  src/styles/table.less
  src/styles/tag.less
  src/styles/themes/antd.less
  src/styles/themes/base.less
  src/styles/themes/bootstrap.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/styles/themes/vars-inject.less
  src/styles/tooltip.less
  src/styles/treeSelect.less
  src/utils/color.js
  src/utils/css-accessors.js
  src/utils/expose.js
  src/utils/index.js
  src/utils/vars-inject.js
  test/utils/expose.spec.js
  webpack/loaders/var-polyfill-loader.js
  webpack/utils/theme.css.js
Labels: feature

#308 add changelog
  site/App.js
  site/pages/documentation/changelog/1.x.x.md
  site/pages/documentation/index.js
Labels: docs

#307 Select
  src/List/AbsoluteList.js
  src/Select/OptionTree.js
  src/Select/Select.js
  src/TreeSelect/TreeSelect.js
Labels: add props

#297 remove old useage
  site/chunks/Components/Form.js
  site/pages/components/Form/b-example-93-validate.js
  site/pages/components/Form/b-example-94-loop.js
  site/pages/components/Form/b-example-95-block.js
  site/pages/components/Form/b-example-96-block.js
  site/pages/components/Form/b-example-97-nested.js
  site/pages/components/Form/b-example-98-block-field.js
  site/pages/components/Form/example-19-nested.js
Labels: docs

#296 Table
  site/chunks/Components/Table.js
  site/pages/components/Table/example-21-drag-column.js
  site/styles/home.less
  src/Table/SeperateTable.js
  src/Table/Table.js
  src/Table/Tbody.js
  src/Table/Thead.js
  src/Table/Tr.js
  src/Table/resizable.js
  src/styles/button.less
  src/styles/table.less
  src/utils/shallowEqual.js
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: add props

#310 Table
  site/pages/components/Upload/example-06-error.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
  src/Table/TreeExpand.js
Labels: bug

#312 Menu
  src/Menu/Item.js
Labels: bug

#311 React warning
  site/Components/Example/index.js
  site/Components/ThemeEditor/index.js
  site/pages/components/Carousel/example-1-base.js
  site/pages/components/Form/b-example-00-fieldset.js
  site/pages/components/Form/b-example-94-loop.js
  site/pages/components/Form/b-example-96-block.js
  site/pages/components/Form/example-13-func-field.js
  site/pages/components/Form/example-15-fieldset.js
  site/pages/components/Form/example-16-fieldset.js
  site/pages/components/Modal/example-5-multistage.js
  site/pages/components/Tabs/example-05-active.js
  site/pages/components/Tree/example-data.js
  src/Alert/index.js
  src/Breadcrumb/index.js
  src/Carousel/index.js
  src/Cascader/Result.js
  src/DatePicker/Icon.js
  src/Dropdown/Item.js
  src/Dropdown/index.js
  src/Image/Gallery.js
  src/Image/Image.js
  src/Input/Number.js
  src/Menu/Item.js
  src/Modal/Panel.js
  src/Pagination/Item.js
  src/Select/Result.js
  src/Table/Sorter.js
  src/Tree/Content.js
  src/TreeSelect/Result.js
  src/Upload/File.js
  src/Upload/ImageFile.js
  src/Upload/ImageResult.js
  src/Upload/Result.js
  test/src/Message/__snapshots__/Message.spec.js.snap
  test/src/Modal/__snapshots__/Modal.spec.js.snap
  test/src/Modal/__snapshots__/Modal.type.spec.js.snap
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Tree/__snapshots__/Tree.spec.js.snap
Labels: bug

#313 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Tr.js
Labels: bug

#314 Radio
  site/chunks/Components/Radio.js
  site/pages/components/Radio/example-6-button-1.js
  site/pages/components/Radio/example-6-button-2.js
  site/pages/components/Radio/example-6-button-3.js
  site/pages/components/Radio/example-6-disabled.js
  site/pages/components/Radio/example-7-disabled.js
  site/pages/components/Radio/example-8-disabled.js
  src/Radio/Group.js
  src/styles/checkinput.less
  test/src/Radio/Radio.spec.js
  test/src/Radio/__snapshots__/example.spec.js.snap
Labels: feature

#316 DatePicker
  src/DatePicker/Day.js
  src/Select/Select.js
Labels: bug
