Repository sheinsight/shineout, pull requests merged in 2020-02, with the labels that each got.

#516 config.delay
  site/pages/components/GetStart/cn.md
  site/pages/components/GetStart/en.md
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/index.d.ts
  src/config.js
  src/hoc/delay.js
Labels: feature

#514 use intersectionObserver
  src/utils/lazyload.js
Labels: feature

#521 add throttle when table resizing
  src/Scroll/Scroll.js
  src/Table/Expand.js
  src/utils/lazyload.js
Labels: performace

#520 fix tree table expand bound when scroll
  src/Table/SeperateTable.js
Labels: bug

#519 Input
  src/Input/Input.js
Labels: bug

#518 Table fixed auto
  site/chunks/Components/Table.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-06-fixed-header.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Table.js
  src/Table/fixedAuto.js
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: feature

#522 transfer onFilter
  site/pages/components/Transfer/cn.md
  site/pages/components/Transfer/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Transfer/Card.js
Labels: feature

#523 transfer onSearch
  site/pages/components/Transfer/cn.md
  site/pages/components/Transfer/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Transfer/Card.js
  src/Transfer/Transfer.js
Labels: add props

#524 Select
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Result.js
Labels: feature

#525 Table
  src/Table/fixedAuto.js
Labels: bug

#528 Sticky
  scripts/create-style.js
  src/Sticky/index.js
Labels: feature

#530 Table.Sorter
  site/chunks/Components/Table.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-10-sort.js
  src/Table/SeperateTable.js
  src/Table/Sorter.js
  src/Table/index.js
Labels: feature

#531 Popover
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  src/Popover/Panel.js
  src/Popover/events.js
  src/styles/popover.less
Labels: feature

#532 Table-Expand
  src/Table/Tr.js
Labels: bug

#533 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/dropdown.less
Labels: bug

#535 Input
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Input/Input.js
Labels: feature

#536 Table.ratio
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Scroll/Scroll.js
  src/styles/datepicker.less
  src/styles/dropdown.less
  src/styles/expose.less
  src/styles/select.less
  src/styles/themes/cssvar.less
  src/styles/treeSelect.less
  src/utils/expose.js
  src/utils/vars-inject.js
Labels: feature

#541 Datepicker
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Range.js
  src/Scroll/Scroll.js
  src/styles/themes/cssvar.less
Labels: bug

#540 Table
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  src/Table/Table.js
Labels: bug

#538 Theme
  src/styles/dropdown.less
  src/styles/expose.less
  src/styles/themes/cssvar.less
  src/utils/css-accessors.js
  src/utils/vars-inject.js
Labels: feature

#537 Modal
  src/Modal/events.js
Labels: bug

#544 Checkbox
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/checkinput.less
  src/styles/expose.less
  src/styles/mixins/close.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: bug

#543 Tabs
  src/Table/index.d.ts
  src/utils/is.js
Labels: bug

#542 modal Select
  src/Modal/Panel.js
  src/Scroll/context.js
Labels: bug
