Repository sheinsight/shineout, pull requests merged in 2020-03, with the labels that each got.

#545 Menu
  src/Menu/Root.js
Labels: bug

#546 fix: Tabs.Link support onClick
  src/Tabs/Link.js
Labels: bug

#548 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/popover.less
Labels: bug

#547 Form-Item
  src/styles/form.less
  src/utils/uid.js
Labels: bug

#549 fix: select
  site/pages/documentation/changelog-rc/1.x.x.md
  src/List/AbsoluteList.js
  src/Modal/Panel.js
Labels: bug

#555 Tree
  src/styles/expose.less
  src/styles/themes/cssvar.less
  src/styles/tree.less
  src/utils/vars-inject.js
Labels: theme

#554 Menu
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  src/Menu/Item.js
  src/Menu/List.js
Labels: feature

#552 EditableArea
  site/pages/components/EditableArea/cn.md
  site/pages/components/EditableArea/en.md
  src/EditableArea/EditableArea.js
  src/styles/editableArea.less
  src/styles/form.less
  src/styles/index.js
  src/utils/dom/element.js
  src/utils/uid.js
Labels: feature

#551 Table
  scripts/build-es5.js
  site/pages/components/Table/example-12-pagination.js
  src/Table/Thead.js
  src/utils/shallowEqual.js
Labels: bug

#550 Change invalid ext show
  src/Upload/Image.js
  src/locale/en_US.js
  src/locale/zh-CN.js
  src/styles/upload.less
  src/utils/index.js
Labels: feature

#553 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
  src/Popover/events.js
  src/styles/popover.less
  src/styles/themes/cssvar.less
  src/utils/css-accessors.js
  src/utils/vars-inject.js
  test/src/Popover/Popover.spec.js
  test/src/Popover/__snapshots__/Popover.spec.js.snap
Labels: feature

#556 Theme
  src/Scroll/Scroll.js
  src/config.js
  src/hoc/trim.js
  src/styles/expose.less
  src/styles/popover.less
  src/styles/themes/cssvar.less
  src/utils/expose.js
  src/utils/vars-inject.js
Labels: feature

#557 fix week quick select bug
  src/DatePicker/Range.js
  src/DatePicker/utils.js
Labels: bug

#558 setValue dispatch
  scripts/build-es5.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/Form.js
Labels: bug

#560 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/themes/antd.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: theme

#561 fix menu expand bug when defaultopenkeys is async
  src/Menu/Item.js
  src/Menu/Root.js
Labels: bug

#562 TS
  scripts/component-declare.ejs
Labels: bug

#563 DataPicker
  src/DatePicker/Day.js
Labels: bug

#564 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
Labels: bug

#566 Select
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/select.less
  src/styles/treeSelect.less
Labels: bug

#565 Table
  src/Table/Tbody.js
Labels: bug

#568 deepRemove
  src/utils/objects.js
  test/utils/getset.spec.js
Labels: bug

#567 Popover
  src/Popover/Panel.js
  src/Popover/context.js
  test/src/Table/Table.spec.js
Labels: bug

#574 Select
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Result.js
  src/styles/select.less
Labels: feature

#573 Tabs
  src/styles/tabs.less
Labels: bug

#572 Theme
  site/Components/ThemeEditor/EditorItem.js
  site/pages/components/Button/cn.md
  site/pages/components/Button/en.md
  src/Button/Button.js
  src/styles/button.less
  src/styles/checkinput.less
  src/styles/expose.less
  src/styles/form.less
  src/styles/normalize.less
  src/styles/themes/antd.less
  src/styles/themes/base.less
  src/styles/themes/bootstrap.less
  src/styles/themes/cssvar.less
  src/styles/themes/vars-inject.less
  src/utils/css-accessors.js
  src/utils/vars-inject.js
  test/src/Button/Button.spec.js
Labels: feature

#571 Validate box from div to popover
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  src/Popover/Panel.js
  src/hoc/inputBorder.js
  src/styles/popover.less
  src/utils/cleanProps.js
  test/src/Input/Input.spec.js
Labels: add props

#575 add info props for Input
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  src/Input/Input.js
Labels: add props

#577 Theme
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Spin/index.js
  src/Table/Tr.js
  src/config.js
  src/styles/checkinput.less
  src/styles/expose.less
  src/styles/table.less
  src/styles/themes/base.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: bug

#579 Cascader
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Cascader.js
Labels: bug

#578 Radio
  src/Checkbox/CheckItem.js
  src/styles/checkinput.less
Labels: bug

#581 add iconfont symbol support
  site/chunks/Components/Icon.js
  site/pages/components/Icon/cn.md
  site/pages/components/Icon/en.md
  site/pages/components/Icon/example-2-iconfont.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Icon/Icon.js
  src/Icon/index.js
  src/styles/icon.less
Labels: feature
