Repository sheinsight/shineout, pull requests merged in 2020-09, with the labels that each got.

#798 fix: tree-table row-select same value
  src/Datum/List.js
  src/Table/CheckboxAll.js
Labels: bug

#799 fix: Carousel children 1 to more not slider
  src/Carousel/index.js
Labels: bug

#800 Upload add forceAccept
  package.json
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Upload/Image.js
  src/Upload/Upload.js
  src/Upload/accept.js
  src/locale/en_US.js
  src/locale/zh-CN.js
Labels: feature

#805 fix: re-render table in scaling modal
  site/chunks/Components/Modal.js
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/components/Modal/example-8-type.js
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  src/Modal/Panel.js
  src/Modal/events.js
  src/styles/modal.less
  test/src/Modal/__snapshots__/Modal.spec.js.snap
  test/src/Modal/__snapshots__/Modal.type.spec.js.snap
Labels: bug, feature

#806 feat: select add columnsTitle
  package.json
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/BoxList.js
  src/Select/Select.js
  src/styles/select.less
Labels: feature

#809 feat: menu render add index
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  src/Menu/Item.js
  src/Menu/Root.js
Labels: feature

#808 fix: visual-table in scaling modal
  site/pages/components/Modal/example-6-close.js
  src/Modal/Panel.js
  src/Modal/events.js
Labels: bug

#811 fix: table resize add column
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/resizable.js
Labels: bug

#818 fix: card in modal padding error
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/modal.less
Labels: bug

#815 fix: tabs button align right
  site/chunks/Components/Radio.js
  site/pages/components/Radio/example-9-toggle.js
  src/Tabs/Header.js
  src/styles/tabs.less
  test/src/Radio/__snapshots__/example.spec.js.snap
Labels: bug

#816 fix: table column
  src/Table/resizable.js
Labels: bug

#814 Shineout style
  config.js
  site/Header.js
  site/utils/theme.js
  src/styles/button.less
  src/styles/dropdown.less
  src/styles/expose.less
  src/styles/select.less
  src/styles/slider.less
  src/styles/themes/base.less
  src/styles/themes/cssvar.less
  src/styles/themes/shineout.less
  src/styles/treeSelect.less
Labels: theme

#819 fix: modal usePortal(false) re-render not work
  site/App.js
  src/Modal/Modal.js
Labels: bug

#820 fix: select onChange not change value no-render
  src/Select/index.js
Labels: bug

#822 fix: DatePicker inputable click to focus
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Text.js
  src/Table/resizable.js
Labels: bug

#824 fix: modal ReactDOM.render inner input blur
  src/Modal/events.js
Labels: bug

#826 feat: add config export
  src/index.js
Labels: bug

#827 fix: theader-group resize error
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Thead.js
Labels: bug

#828 fix: select option line-height update
  package.json
  site/pages/components/Message/cn.md
  site/pages/components/Message/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Select.js
Labels: bug

#831 new Theme Editor
  package.json
  site/Components/ThemeEditor/Drawer.js
  site/Components/ThemeEditor/Editor.js
  site/Components/ThemeEditor/EditorItem.js
  site/Components/ThemeEditor/Fab.js
  site/Components/ThemeEditor/config.js
  site/Components/ThemeEditor/index.js
  site/Header.js
  site/pages/documentation/changelog-rc/1.x.x.md
  site/styles/editor.less
  site/styles/fab.less
  site/styles/index.js
  src/Form/Form.js
  src/hoc/resizable.js
  src/styles/resizable.less
Labels: feature

#832 docs
  package.json
  site/pages/components/Input/cn.md
  site/pages/components/Input/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
Labels: docs

#834 fix: onEnterPress fire
  src/Input/Input.js
Labels: bug

#836 fix: sticky shaking
  src/Sticky/index.js
Labels: bug

#837 feat: time add defaultTime
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Time.js
Labels: feature

#838 fix: input blur value-change no render
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/hoc/delay.js
Labels: bug

#840 fix:data change re-fixed
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Icon/index.js
  src/Table/fixedAuto.js
Labels: bug
