Repository sheinsight/shineout, pull requests merged in 2020-06, with the labels that each got.

#654 Modal.destory
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Modal/Modal.js
  src/Modal/events.js
  src/styles/popover.less
Labels: feature

#650 Tabs
  src/Tabs/Tab.js
Labels: feature

#649 Tooltop
  src/Tooltip/events.js
Labels: bug

#660 Slider
  site/chunks/Components/Slider.js
  site/pages/components/Slider/example-01-input.js
Labels: feature

#661 Theme
  src/Tabs/Tab.js
  src/styles/card.less
  src/styles/checkinput.less
  src/styles/expose.less
  src/styles/message.less
  src/styles/modal.less
  src/styles/slider.less
  src/styles/table.less
  src/styles/tag.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: theme

#664 Tree
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/Tree.js
  src/TreeSelect/datum.js
Labels: bug

#665 Modal
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  src/Modal/Panel.js
Labels: feature

#666 Lazyload
  src/utils/lazyload.js
Labels: bug

#667 Popover
  src/Popover/Panel.js
Labels: bug

#668 optimize
  src/hoc/hidable.js
Labels: feature

#670 Tree
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/select.less
  src/styles/tree.less
Labels: bug

#673 Cascader
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  src/Cascader/Cascader.js
Labels: feature

#674 Select-TreeData
  src/Select/Select.js
Labels: bug

#677 Select
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Select.js
Labels: bug

#678 update test
  .travis.yml
  src/Popover/Panel.js
  test/src/Cascader/Cascader.spec.js
  test/src/Datum/Tree.spec.js
  test/src/Dropdown/Dropdown.spec.js
  test/src/EditableArea/EditableArea.spec.js
  test/src/EditableArea/__snapshots__/example.spec.js.snap
  test/src/Form/Form.spec.js
  test/src/Message/__snapshots__/Message.spec.js.snap
  test/src/Popover/Popover.spec.js
  test/src/Slider/__snapshots__/example.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Tag/__snapshots__/example.spec.js.snap
Labels: Build

#680 Select
  src/Select/filter.js
Labels: bug

#685 Popover
  site/pages/components/Popover/example-10-container.js
  src/Popover/Panel.js
Labels: bug

#686 Pagination
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Pagination/Jumper.js
Labels: bug

#693 Tree
  site/pages/components/Image/cn.md
  site/pages/components/Image/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/Tree.js
  src/Image/Image.js
Labels: bug

#695 Theme
  src/styles/themes/antd.less
  src/styles/themes/bootstrap.less
  src/utils/vars-inject.js
Labels: bug

#696 fix: optimize modal component transition effect
  src/Card/Card.js
  src/Modal/Panel.js
  src/hoc/resizable.js
  src/styles/modal.less
Labels: bug

#697 CardGroup
  site/chunks/Components/CardGroup.js
  site/pages/components/CardGroup/cn.md
  site/pages/components/CardGroup/en.md
  site/pages/components/CardGroup/example-2-widthMax.js
  src/CardGroup/CardGroup.js
  src/styles/cardGroup.less
Labels: bug

#699 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/popover.less
Labels: bug

#700 style fix
  src/styles/modal.less
Labels: bug

#703 Lazyload
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/CardGroup/Item.js
  src/Lazyload/index.js
  src/styles/index.js
  src/styles/lazyload.less
Labels: bug

#704 Tree
  src/Tree/Tree.js
Labels: bug

#706 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Carousel/index.js
  src/Scroll/Scroll.js
  src/Table/Tr.js
  test/src/Carousel/Carousel.spec.js
Labels: bug
