Repository sheinsight/shineout, pull requests merged in 2020-08, with the labels that each got.

#760 feat: Upload add onErrorRemove
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  src/Upload/File.js
  src/Upload/Result.js
  src/Upload/Upload.js
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: feature

#759 feat: TreeSelect & Cascader add onCollapse
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  site/pages/components/TreeSelect/cn.md
  site/pages/components/TreeSelect/en.md
  src/Cascader/Cascader.js
  src/TreeSelect/TreeSelect.js
Labels: feature

#762 Changelog
  site/pages/documentation/changelog-rc/1.x.x.md
Labels: changelog

#768 feat: Modal.Submit add disabled
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Card/Submit.js
Labels: feature

#766 feat: menu add onOpenChange
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  src/Menu/Root.js
Labels: feature

#771 fix: modal position popup with scrollbar
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/modal.less
Labels: bug

#770 feat: message add close-single
  site/chunks/Components/Message.js
  site/pages/components/Message/example-5-manual-close.js
  src/Message/Container.js
  src/Message/index.js
Labels: feature

#782 fix: babel Iterator to array transform error
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Menu/Root.js
Labels: bug

#780 fix: theme line-height truncated
  src/styles/expose.less
  src/utils/vars-inject.js
Labels: bug

#772 fix: clientWidth Ignore the decimal point
  package.json
  src/Table/SeperateTable.js
Labels: bug

#784 fix: wrong width under inline-form
  src/styles/editableArea.less
Labels: bug

#785 fix: Table tr float make scrollbar error
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Scroll/Scroll.js
  src/Table/Tr.js
Labels: bug

#786 feat: add autoSSL
  site/pages/components/Image/cn.md
  site/pages/components/Image/en.md
  src/Image/Image.js
  src/config.js
  src/utils/strings.js
Labels: feature

#793 fix: EditableArea clearable cant trigger onChange event
  src/EditableArea/EditableArea.js
Labels: bug
