Repository sheinsight/shineout, pull requests merged in 2020-04, with the labels that each got.

#583 Table
  src/styles/themes/cssvar.less
Labels: bug

#588 Button
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/button.less
Labels: bug

#587 Table-Resize
  src/Table/resizable.js
Labels: bug

#586 Select-onCreate
  src/Select/Result.js
Labels: bug

#585 TreeTable
  src/styles/expose.less
  src/styles/table.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: theme

#584 Select
  src/Select/Select.js
  test/src/Icon/__snapshots__/example.spec.js.snap
Labels: bug

#590 PropTypes
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/Tr.js
Labels: bug

#582 Table multiple sort
  site/chunks/Components/Table.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-10-sort-default.js
  site/pages/components/Table/example-10-sort-weight.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Sorter.js
  src/Table/Thead.js
  src/Table/index.js
  test/src/Table/Table.sort.spec.js
Labels: feature

#593 EditableArea
  site/pages/documentation/changelog-rc/1.x.x.md
  src/EditableArea/EditableArea.js
  src/styles/editableArea.less
Labels: bug

#592 Font size
  src/styles/select.less
  src/styles/themes/antd.less
  src/styles/themes/base.less
  src/styles/themes/bootstrap.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: theme

#594 Theme
  src/config.js
  src/utils/expose.js
  src/utils/vars-inject.js
Labels: bug

#597 Datepicker
  site/chunks/Components/Pagination.js
  site/pages/components/Pagination/example-9-modal.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Day.js
  src/DatePicker/Range.js
Labels: feature

#595 Sticky
  src/Sticky/index.js
Labels: bug

#598 Modal
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/expose.less
  src/styles/modal.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: New Component

#599 Input
  src/Input/Input.js
Labels: bug

#600 Modal
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/expose.less
  src/styles/modal.less
  src/styles/themes/antd.less
  src/styles/themes/cssvar.less
  src/styles/themes/default.less
  src/utils/vars-inject.js
Labels: theme

#602 Popover
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
Labels: bug

#601 Tabs
  src/styles/tabs.less
Labels: bug

#604 Tooltip
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
  src/Table/fixedAuto.js
  src/styles/tooltip.less
Labels: bug

#605 Rate
  src/Icon/index.js
  src/Rate/Rate.js
  src/styles/datepicker.less
Labels: bug

#606 Theme
  site/pages/components/Popover/example-3-click.js
  src/Dropdown/index.js
  src/Modal/Panel.js
  src/icons/index.js
  src/styles/card.less
  src/styles/checkinput.less
  src/styles/dropdown.less
  src/styles/expose.less
  src/styles/form.less
  src/styles/message.less
  src/styles/modal.less
  src/styles/select.less
  src/styles/slider.less
  src/styles/table.less
  src/styles/themes/antd.less
  src/styles/themes/bootstrap.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: theme

#608 Table
  src/Table/Colgroup.js
  src/Table/SeperateTable.js
  src/Table/SimpleTable.js
  src/Table/Thead.js
  src/Table/resizable.js
Labels: bug

#610 Popover
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Popover/Panel.js
  src/Popover/events.js
Labels: bug
