Repository sheinsight/shineout, pull requests merged in 2020-01, with the labels that each got.

#483 transform input .
  src/Input/Input.js
Labels: bug

#481 Transfer & check
  site/pages/components/Transfer/example-3-customTitle.js
  src/Transfer/item.js
  src/styles/checkinput.less
  src/styles/transfer.less
  test/src/Transfer/__snapshots__/example.spec.js.snap
Labels: bug

#484 changelog
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  yarn.lock
Labels: docs

#490 AbsoluteList
  site/pages/documentation/changelog-rc/1.x.x.md
  src/List/AbsoluteList.js
  src/Select/BoxList.js
  src/Select/OptionTree.js
Labels: feature

#489 fix table sorter position bugs
  src/Table/Thead.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.loading.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Table/__snapshots__/Table.rowClassname.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: bug

#488 Select
  src/styles/select.less
Labels: feature

#487 fix tooltip hover bug
  src/Tooltip/Container.js
  src/Tooltip/events.js
Labels: bug

#486 group disabled style
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/form.less
Labels: bug

#482 fix datapicker and menu bugs
  src/DatePicker/Container.js
  src/Menu/Item.js
Labels: bug

#479 Add table column min with props
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/SeperateTable.js
  src/Table/SimpleTable.js
  src/Table/Tbody.js
  src/styles/table.less
  test/src/Table/Table.expand.spec.js
  test/src/Table/Table.spec.js
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.loading.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Table/__snapshots__/Table.rowClassname.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: add props

#494 Fix table placeholder bug
  src/Table/Tbody.js
  src/styles/table.less
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: bug

#493 Table
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  src/Table/SeperateTable.js
  src/Table/SimpleTable.js
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: feature

#492 fix menu links click bug
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Menu/Item.js
Labels: bug

#501 Menu
  site/chunks/Components/Menu.js
  site/pages/components/Menu/cn.md
  site/pages/components/Menu/en.md
  site/pages/components/Menu/example-3-vertical.js
  src/Menu/Item.js
  src/Menu/List.js
  src/Menu/Root.js
Labels: feature

#500 Image
  site/pages/components/Image/cn.md
  site/pages/components/Image/en.md
  src/Image/Image.js
  src/Lazyload/index.js
  src/utils/lazyload.js
Labels: feature

#499 Popover
  site/pages/components/Popover/cn.md
  site/pages/components/Popover/en.md
  site/pages/components/Popover/example-3-click.js
  src/Popover/Panel.js
Labels: feature

#497 Select.BoxList
  src/Select/BoxOption.js
Labels: bug

#496 changelog
  site/pages/documentation/changelog-rc/1.x.x.md
Labels: bug

#495 Theme
  src/styles/popover.less
Labels: bug

#498 Fix editable datapicker blur bug
  src/DatePicker/Container.js
  src/DatePicker/Text.js
Labels: bug

#506 Datepicker range
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  site/pages/components/DatePicker/example-09-range-date.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/Day.js
  src/DatePicker/Range.js
  src/DatePicker/Time.js
  yarn.lock
Labels: feature

#502 add EditableArea component
  site/chunks/Components/EditableArea.js
  site/chunks/Components/index.js
  site/pages/components/EditableArea/cn.md
  site/pages/components/EditableArea/en.md
  site/pages/components/EditableArea/example-1-base.js
  site/pages/components/EditableArea/example-2-controlled.js
  site/pages/components/group.json
  src/EditableArea/EditableArea.js
  src/EditableArea/index.js
  src/index.js
  src/styles/form.less
  src/styles/index.js
  test/src/EditableArea/EditableArea.spec.js
  test/src/EditableArea/__snapshots__/example.spec.js.snap
  test/src/EditableArea/example.spec.js
Labels: New Component

#505 add filesFilter props
  site/pages/components/Upload/cn.md
  site/pages/components/Upload/en.md
  src/Upload/Upload.js
Labels: add props

#507 Table
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Tbody.js
Labels: bug

#508 docs
  README-zh_CN.md
  README.md
  site/chunks/Components/Tabs.js
  site/pages/components/Tabs/example-12-extra.js
Labels: docs

#512 Add table disabled and bordered
  site/pages/components/EditableArea/cn.md
  site/pages/components/EditableArea/en.md
  src/EditableArea/EditableArea.js
  src/styles/form.less
Labels: add props

#510 fix-table-mousemove-bug
  src/Scroll/Bar.js
Labels: bug

#509 Select
  src/Select/filter.js
Labels: bug

#511 Tabs
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tabs/Tabs.js
Labels: bug
