Repository sheinsight/shineout, pull requests merged in 2021-11, with the labels that each got.

#1316 优化 Menu 样式 暗黑模式下选中的父节点菜单 hover 颜色为白色
  src/Menu/styles/menu.less
Labels: bug

#1291 form add size to input
  src/Form/formContext.js
  src/Form/inputable.js
Labels: add props

#1294 column support minWidth maxWidth
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-21-drag-column.js
  src/Table/SeperateTable.js
  src/Table/SimpleTable.js
  src/Table/Tbody.js
  src/Table/Thead.js
  src/Table/index.d.ts
  src/Table/styles/table.less
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.empty.spec.js.snap
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
  test/src/Table/__snapshots__/Table.group.spec.js.snap
  test/src/Table/__snapshots__/Table.loading.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
  test/src/Table/__snapshots__/Table.rowClassname.spec.js.snap
  test/src/Table/__snapshots__/Table.spec.js.snap
Labels: add props

#1285 Update date-fns to 2.0.0-alpha.11 Fix the return value error of the p…
  package.json
  site/data/user.js
  site/pages/components/DatePicker/example-09-squick.js
  site/pages/components/DatePicker/example-11-disabled-type.js
  site/pages/components/DatePicker/example-11-disabled.js
  site/pages/components/Form/b-example-00-base.js
  site/utils/faker/index.js
  src/DatePicker/Day.js
  src/DatePicker/Month.js
  src/DatePicker/Picker.js
  src/DatePicker/Range.js
  src/DatePicker/Time.js
  src/DatePicker/TimeScroll.js
  src/DatePicker/Year.js
  src/DatePicker/paramUtils.js
  src/DatePicker/utils.js
  test/src/DatePicker/DatePicker.spec.js
  test/utils/dateUtils.spec.js
  yarn.lock
Labels: feature
