Repository sheinsight/shineout, pull requests merged in 2021-03, with the labels that each got.

#1024 fix: popover hover dismiss on firefix
  src/styles/popover.less
Labels: bug

#1023 datepicker add formatResult example
  site/chunks/Components/DatePicker.js
  site/pages/components/DatePicker/example-02-format.js
  site/pages/components/DatePicker/example-09-range-date.js
Labels: docs

#1025 Feat/cascader support single del
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  src/Cascader/Cascader.js
  src/Cascader/Result.js
  src/Cascader/index.d.ts
  src/styles/cascader.less
Labels: feature

#1026 feat: table add rowClickAttr with true
  package.json
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-25-row-click-attr.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/Tr.js
Labels: feature

#1028 fix: table drag to bottom data dismiss
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/SeperateTable.js
Labels: bug

#1032 fix: table big data scroll error
  src/Table/SeperateTable.js
Labels: bug

#1033 Fix/select tree node width
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/OptionTree.js
  src/styles/select.less
Labels: bug

#1036 fix: Checkbox.Group in blocked Group
  src/Checkbox/Group.js
  src/styles/checkinput.less
Labels: bug

#1037 Feat/cascader unmated value
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Result.js
  src/Datum/Tree.js
Labels: feature

#1041 feat: opti datepicker doc
  site/pages/components/DatePicker/example-01-base.js
  site/pages/components/DatePicker/example-04-minmax.js
  site/pages/components/DatePicker/example-09-range-date.js
  site/pages/components/DatePicker/example-09-range-month.js
  site/pages/components/DatePicker/example-09-single.js
  site/pages/components/DatePicker/example-09-squick.js
  src/DatePicker/Text.js
Labels: docs

#1040 fix: spin zindex cover select option and transfer body zindex
  src/Spin/index.d.ts
  src/styles/spin.less
  src/styles/transfer.less
Labels: bug

#1042 fix: datum.tree remove style
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/Tree.js
Labels: bug

#1044 Fix/treeselect input
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/TreeSelect/Input.js
  src/styles/treeSelect.less
Labels: bug

#1046 fix: cascader data change reset unmated value
  src/Datum/Tree.js
Labels: bug

#1045 fix: Dropdown can't dismiss
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Dropdown/index.js
Labels: bug

#1047 Feat/select hide create option
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/OptionList.js
  src/Select/Select.js
  src/Select/filter.js
  src/Select/index.d.ts
Labels: feature

#1055 fix: input disabled number with no style
  src/hoc/inputBorder.js
Labels: bug

#1056 fix: checkbox cancel value 0
  src/Datum/List.js
Labels: bug

#1058 fix: form un-controll while item unmount
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/hoc.js
Labels: bug

#1059 Table select
  src/Table/CheckboxAll.js
Labels: bug

#1060 Feat/message hide close
  package.json
  site/pages/components/Alert/cn.md
  site/pages/components/Alert/en.md
  site/pages/components/Message/cn.md
  site/pages/components/Message/en.md
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Alert/index.d.ts
  src/Alert/index.js
  src/Message/Container.js
  src/Message/index.d.ts
  src/Message/index.js
  test/src/Message/__snapshots__/Message.spec.js.snap
Labels: feature

#1061 feat: radio renderItem add index
  src/Radio/Group.js
Labels: feature

#1062 fix: input.number blur with onchange
  src/Input/Number.js
  src/utils/validate/rangeLength.js
Labels: bug

#1063 fix: build ts to dist
  package.json
  scripts/build-es5.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Datum/hoc.js
  src/Input/index.js
Labels: bug

#1064 fix: update common ts
  src/@types/common.d.ts
Labels: bug

#1065 fix: input.number override
  package.json
  src/Input/index.js
Labels: bug

#1067 fix: select onfilter paste
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Input.js
  src/styles/select.less
  src/styles/treeSelect.less
Labels: bug, feature

#1070 feat: datepicker add defaultPickerValue
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  src/DatePicker/Container.js
  src/DatePicker/index.d.ts
Labels: feature

#1071 feat: upload add request ignore example
  package.json
  site/chunks/Components/Upload.js
  site/pages/components/Upload/example-08-request-a.js
  site/pages/components/Upload/example-08-request-ignore.js
  site/pages/documentation/changelog-rc/1.x.x.md
  test/src/Upload/__snapshots__/example.spec.js.snap
Labels: feature

#1072 fix: cascader clearable
  src/styles/cascader.less
Labels: bug

#1073 fix: table check header status
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Table/CheckboxAll.js
  src/utils/validate/rangeLength.js
Labels: bug
