Repository sheinsight/shineout, pull requests merged in 2021-01, with the labels that each got.

#942 Fix/css accessor
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/styles/expose.less
  src/utils/vars-inject.js
Labels: bug

#944 fix: select value 0 not show
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Result.js
Labels: bug

#947 Fix/datepicker tolocaltimestring convert error
  package.json
  site/Components/Eggs.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/DatePicker/utils.js
Labels: bug

#949 fix: upload.image renderContent can't preview
  package.json
  site/pages/components/Form/cn.md
  site/pages/components/Form/en.md
  site/pages/components/Select/cn.md
  site/pages/components/Table/example-01-base.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Form/Item.js
  src/Form/formContext.js
  src/Form/index.js
  src/Pagination/Item.js
  src/Upload/ImageResult.js
  src/styles/form.less
  src/styles/table.less
  test/src/Pagination/Pagination.spec.js
  test/src/Table/Table.pagination.spec.js
  test/src/Table/__snapshots__/Table.combine.spec.js.snap
  test/src/Table/__snapshots__/Table.pagination.spec.js.snap
Labels: bug

#950 fix: formElemement Rule can't validate clearable
  package.json
  site/pages/components/DatePicker/example-09-squick.js
  site/pages/components/Modal/cn.md
  site/pages/components/Modal/en.md
  site/pages/components/Modal/example-9-zoom.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Form/inputable.js
  src/Modal/Panel.js
Labels: bug

#954 fix: example reset
  site/pages/components/Table/example-01-base.js
Labels: bug

#956 Feat/cascader on filter
  package.json
  site/chunks/Components/Cascader.js
  site/pages/components/Cascader/cn.md
  site/pages/components/Cascader/en.md
  site/pages/components/Cascader/example-06-filter.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Cascader/Cascader.js
  src/Cascader/FilterList.js
  src/Cascader/Input.js
  src/Cascader/Node.js
  src/Cascader/Result.js
  src/Cascader/filter.js
  src/Cascader/index.js
  src/styles/cascader.less
  src/utils/tree.js
Labels: feature

#955 Feat/table focus click
  package.json
  site/chunks/Components/Table.js
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-32-selection.js
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Button/Group.js
  src/Table/Table.js
  src/Table/Td.js
  src/Table/index.d.ts
  src/Table/select.js
  src/styles/table.less
  src/utils/dom/document.js
  src/utils/is.js
  test/src/Table/__snapshots__/Table.expand.spec.js.snap
Labels: feature

#964 feat: ts d.ts mention
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  tsconfig.json
  yarn.lock
Labels: feature

#963 feat: formatResult supoort func
  site/pages/components/DatePicker/cn.md
  site/pages/components/DatePicker/en.md
  src/DatePicker/Container.js
  src/DatePicker/Text.js
  src/DatePicker/index.d.ts
  src/DatePicker/utils.js
Labels: feature

#962 feat: select renderResult add string
  src/Select/Result.js
  src/Select/Select.js
Labels: feature

#966 Feat/table rename selection
  site/chunks/Components/Table.js
  site/pages/components/CardGroup/cn.md
  site/pages/components/CardGroup/en.md
  site/pages/components/Table/cn.md
  site/pages/components/Table/en.md
  site/pages/components/Table/example-32-selection.js
  src/CardGroup/CardGroup.js
  src/Table/select.js
Labels: feature

#969 feat: tabs add autoFill
  site/chunks/Components/Tabs.js
  site/pages/components/Tabs/cn.md
  site/pages/components/Tabs/en.md
  site/pages/components/Tabs/example-12-auto-fill.js
  src/Tabs/Tabs.js
  src/styles/tabs.less
Labels: feature

#973 fix: tree drag index error
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Tree/Node.js
Labels: bug

#972 Feat/list fixed
  site/chunks/Components/List.js
  site/chunks/Components/Select.js
  site/chunks/Components/Transfer.js
  site/pages/components/List/cn.md
  site/pages/components/List/en.md
  site/pages/components/List/example-02-fixed.js
  site/pages/components/Select/example-06-bigdata.js
  site/pages/components/Transfer/example-7-bigdata.js
  src/AnimationList/LazyList.js
  src/DataList/List.js
  src/Scroll/Scroll.js
  src/Select/BoxList.js
  src/styles/list.less
  src/utils/uid.js
Labels: feature

#982 feat: table add top border config
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Transfer/Card.js
  src/styles/expose.less
  src/styles/form.less
  src/styles/table.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: feature

#980 fix: form style fix
  site/chunks/Components/Form.js
  site/pages/components/Form/example-03-label-vertical.js
  src/styles/button.less
  src/styles/form.less
Labels: bug

#987 feat: example support ts
  .babelrc
  .eslintrc
  package.json
  webpack/config.common.js
  yarn.lock
Labels: feature

#978 Feat/cascader ts
  src/Cascader/index.d.ts
Labels: TypeScript

#990 feat: button add min-width
  site/Components/ThemeEditor/Editor.js
  src/styles/button.less
  src/styles/themes/cssvar.less
  src/utils/vars-inject.js
Labels: theme

#991 feat: select add caret to close
  .eslintrc
  package.json
  site/pages/documentation/changelog-rc/1.x.x.md
  src/Select/Select.js
  yarn.lock
Labels: feature

#986 feat: cascader add filter example
  site/pages/components/Cascader/example-06-filter.js
  site/pages/components/Select/cn.md
  site/pages/components/Select/en.md
  site/pages/components/Select/example-08-filter.js
  src/Select/Option.js
  src/Select/OptionList.js
Labels: feature

#981 ts declare of dropdown
  src/Dropdown/index.d.ts
Labels: TypeScript

#993 add common typescript declare and utils
  src/@types/common.d.ts
  src/Alert/index.d.ts
  src/Cascader/index.d.ts
  src/Divider/index.d.ts
  src/Dropdown/index.d.ts
Labels: TypeScript
